# LLMBO优化配置文件
# 基于论文研究结果的最优配置

# LLM API配置
llm:
  api_key: "sk-84ac2d321cf444e799ddc9db79c02e92"
  base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  
  # 模型选择（基于性价比）
  # 选项: qwen-turbo (快), qwen-plus (推荐), qwen-max (最佳), gpt-4o (极致), deepseek-r1 (高性价比)
  model: "qwen-plus"
  
  # 各阶段Temperature配置 (基于论文研究)
  temperature:
    warm_start: 0.9      # 高多样性，广泛探索
    surrogate: 0.5       # 精确物理理解
    sampling_early: 0.7  # 早期探索
    sampling_mid: 0.6    # 中期平衡
    sampling_late: 0.5   # 后期利用
  
  # Token限制
  max_tokens:
    warm_start: 2500
    surrogate: 2000
    sampling: 1800

# 贝叶斯优化配置
bayesian_optimization:
  # 初始采样点数
  init_points: 5
  
  # 优化迭代次数
  n_iter: 25
  
  # Acquisition Function类型
  # 选项: 'PI' (推荐-快充), 'EI' (通用), 'LCB' (高噪声)
  acquisition_type: 'PI'
  
  # PI/EI参数
  xi: 0.01
  
  # LCB参数 (论文推荐beta=4.0)
  beta: 4.0
  
  # 候选点数量
  n_candidates: 1000
  
  # 是否使用参数敏感性分析
  use_sensitivity: true
  
  # 随机种子
  random_state: 1

# 参数边界
parameter_bounds:
  current1:
    min: 3.0
    max: 6.0
    description: "初始充电电流 (A)"
  
  charging_number:
    min: 5
    max: 25
    description: "切换周期数"
  
  current2:
    min: 1.0
    max: 3.0
    description: "最终充电电流 (A)"

# 约束条件
constraints:
  voltage_max: 4.2      # 最大电压 (V)
  temp_max: 309         # 最大温度 (K) = 36°C
  target_soc: 0.8       # 目标SOC

# Latin Hypercube Sampling配置
lhs:
  enabled: true
  fallback_when_llm_fails: true

# 多样性选择配置
diversity_selection:
  method: 'maximin'     # maximin距离算法
  enabled: true

# 参数敏感性分析配置
sensitivity_analysis:
  method: 'morris'      # Morris方法
  threshold_high: 0.4   # 高敏感度阈值
  threshold_low: 0.2    # 低敏感度阈值
  min_samples: 3        # 最小样本数

# 复合核函数配置
composite_kernel:
  gamma_min: 0.5        # 最小耦合强度
  gamma_max: 2.0        # 最大耦合强度
  gamma_default: 1.0    # 默认耦合强度
  
  # 长度尺度范围
  length_scale_ranges:
    current1: [0.3, 0.8]
    charging_number: [1.0, 2.0]
    current2: [0.5, 1.2]

# 可视化配置
visualization:
  # 图像保存设置
  dpi: 300
  format: 'png'
  
  # 电流平滑窗口
  current_smooth_window: 5
  
  # 是否显示原始电流
  show_raw_current: true
  
  # 颜色方案
  colormap:
    convergence: 'viridis'
    parameters: 'plasma'
    comparison: 'coolwarm'

# 日志配置
logging:
  level: 'INFO'         # DEBUG, INFO, WARNING, ERROR
  save_to_file: true
  filename: 'llmbo_optimization.log'
  
  # 显示详细信息
  show_llm_responses: false
  show_sensitivity: true
  show_acquisition_values: false

# 实验配置
experiment:
  # 运行模式: 'bo', 'llmbo', 'both'
  mode: 'llmbo'
  
  # 对比实验
  run_comparison: false
  
  # 保存结果
  save_results: true
  results_dir: './results'
  
  # 重复次数（用于统计分析）
  n_repeats: 1

# 性能优化
performance:
  # 并行评估（如果SPM支持）
  parallel_evaluation: false
  n_jobs: 1
  
  # 缓存设置
  cache_enabled: false
  
  # 早停条件
  early_stopping:
    enabled: false
    patience: 10          # 连续多少次无改进则停止
    min_improvement: 0.1  # 最小改进阈值

# 调试选项
debug:
  # 详细输出
  verbose: true
  
  # 保存中间结果
  save_intermediate: false
  
  # LLM响应保存
  save_llm_responses: false
  
  # 绘制所有迭代的图
  plot_all_iterations: false

# 论文复现配置
paper_reproduction:
  # 是否严格按照论文设置
  strict_mode: false
  
  # 论文使用的模型
  paper_model: 'gpt-4o'
  
  # 论文使用的参数
  paper_settings:
    init_points: 10
    n_iter: 50
    acquisition: 'PI'